/* eslint-disable jsx-a11y/alt-text */
"use client";

import React from 'react';
import { Page, Text, View, Document, StyleSheet, Image, Font } from '@react-pdf/renderer';
import type { Mole, MoleEntry } from '@/db';

// Register a font (optional, but good for custom look)
// For now, we'll use standard fonts to avoid loading issues.

const styles = StyleSheet.create({
    page: {
        padding: 40,
        backgroundColor: '#FFFFFF',
        fontFamily: 'Helvetica',
    },
    header: {
        marginBottom: 20,
        borderBottomWidth: 2,
        borderBottomColor: '#112233',
        paddingBottom: 10,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#112233',
    },
    subtitle: {
        fontSize: 12,
        color: '#666666',
        marginTop: 5,
    },
    disclaimerBox: {
        backgroundColor: '#FFF4F4',
        borderWidth: 1,
        borderColor: '#FF0000',
        padding: 10,
        marginBottom: 20,
        borderRadius: 4,
    },
    disclaimerTitle: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#CC0000',
        marginBottom: 5,
    },
    disclaimerText: {
        fontSize: 10,
        color: '#CC0000',
        lineHeight: 1.4,
    },
    section: {
        marginBottom: 10,
    },
    moleContainer: {
        marginBottom: 25,
        breakInside: 'avoid',
    },
    moleHeader: {
        fontSize: 18,
        fontWeight: 'bold',
        backgroundColor: '#F0F4F8',
        padding: 8,
        marginBottom: 10,
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    moleInfo: {
        fontSize: 12,
        marginBottom: 5,
        color: '#334455',
    },
    entryContainer: {
        marginBottom: 15,
        paddingLeft: 10,
        borderLeftWidth: 2,
        borderLeftColor: '#E0E0E0',
    },
    entryHeader: {
        flexDirection: 'row',
        marginBottom: 5,
    },
    entryDate: {
        fontSize: 12,
        fontWeight: 'bold',
        width: 100,
    },
    entrySize: {
        fontSize: 12,
        color: '#555',
    },
    entryNotes: {
        fontSize: 11,
        marginTop: 4,
        fontStyle: 'italic',
        color: '#444',
    },
    entryRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: 8,
        gap: 10,
    },
    image: {
        width: 150,
        height: 150,
        objectFit: 'cover',
        borderRadius: 4,
        backgroundColor: '#EEE',
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 40,
        right: 40,
        textAlign: 'center',
        fontSize: 9,
        color: '#999',
        borderTopWidth: 1,
        borderTopColor: '#EEE',
        paddingTop: 10,
    },
});

interface PDFReportProps {
    moles: Mole[];
    entries: MoleEntry[];
    selectedMoleIds: number[];
    screenshotMap?: Record<number, string>;
}

const PDFReport = ({ moles, entries, selectedMoleIds, screenshotMap }: PDFReportProps) => {
    // Filter moles and map entries
    const molesToExport = moles.filter(m => selectedMoleIds.includes(m.id!));

    // Group entries by moleId
    const entriesByMoleId = entries.reduce((acc, entry) => {
        if (!acc[entry.moleId]) {
            acc[entry.moleId] = [];
        }
        acc[entry.moleId].push(entry);
        return acc;
    }, {} as Record<number, MoleEntry[]>);

    return (
        <Document>
            <Page size="A4" style={styles.page}>
                {/* Header */}
                <View style={styles.header}>
                    <Text style={styles.title}>Track-A-Mole Report</Text>
                    <Text style={styles.subtitle}>Generated on {new Date().toLocaleDateString()}</Text>
                </View>

                {/* Liability Disclaimer */}
                <View style={styles.disclaimerBox}>
                    <Text style={styles.disclaimerTitle}>IMPORTANT LIABILITY DISCLAIMER</Text>
                    <Text style={styles.disclaimerText}>
                        This report is generated by Track-A-Mole, a personal note-taking application.
                        Track-A-Mole is NOT a diagnostic tool and is NOT a medical device.
                        The information contained in this report, including photos and measurements, is for personal tracking purposes only and should not be used for self-diagnosis.
                        Always consult with a qualified healthcare professional for any concerns regarding your skin health.
                        The developers of Track-A-Mole assume no liability for the accuracy of this data or any health decisions made based on it.
                    </Text>
                </View>

                {/* Mole List */}
                {molesToExport.map((mole) => {
                    const moleEntries = entriesByMoleId[mole.id!] || [];
                    // Sort entries by date descending
                    moleEntries.sort((a, b) => b.date - a.date);

                    return (
                        <View key={mole.id} style={styles.moleContainer} break>
                            <View style={styles.moleHeader}>
                                <View>
                                    <Text>{mole.label}</Text>
                                    <Text style={{ fontSize: 12, fontWeight: 'normal' }}>
                                        {mole.type ? mole.type.toUpperCase() : 'MOLE'}
                                    </Text>
                                </View>
                                {screenshotMap && screenshotMap[mole.id!] && (
                                    <Image
                                        src={screenshotMap[mole.id!]}
                                        style={{ width: 80, height: 80, borderRadius: 4, objectFit: 'cover' }}
                                    />
                                )}
                            </View>

                            {moleEntries.length === 0 ? (
                                <Text style={{ fontSize: 11, color: '#888', fontStyle: 'italic', paddingLeft: 10 }}>
                                    No entries recorded.
                                </Text>
                            ) : (
                                moleEntries.map((entry) => (
                                    <View key={entry.id} style={styles.entryContainer} wrap={false}>
                                        <View style={styles.entryHeader}>
                                            <Text style={styles.entryDate}>
                                                {new Date(entry.date).toLocaleDateString()}
                                            </Text>
                                            <Text style={styles.entrySize}>
                                                Size: {entry.size}mm
                                            </Text>
                                            {entry.severity !== undefined && (
                                                <Text style={{ ...styles.entrySize, marginLeft: 15 }}>
                                                    Severity: {entry.severity}/10
                                                </Text>
                                            )}
                                        </View>

                                        {entry.notes && (
                                            <Text style={styles.entryNotes}>
                                                "{entry.notes}"
                                            </Text>
                                        )}

                                        {/* Photos */}
                                        {entry.photo && (
                                            <View style={styles.entryRow}>
                                                <Image
                                                    src={entry.photo}
                                                    style={styles.image}
                                                />
                                            </View>
                                        )}

                                        {/* Symptoms tag if present */}
                                        {entry.symptoms && entry.symptoms.length > 0 && (
                                            <Text style={{ fontSize: 10, marginTop: 5, color: '#666' }}>
                                                Symptoms: {entry.symptoms.join(', ')}
                                            </Text>
                                        )}
                                    </View>
                                ))
                            )}
                        </View>
                    );
                })}

                <Text style={styles.footer} fixed>
                    Track-A-Mole Report - Generated {new Date().toLocaleDateString()} - Page <Text render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
                </Text>
            </Page>
        </Document>
    );
};

export default PDFReport;
